const cards = [
    {
        i: 0,
        question: "O que é JSX?",
        answer: "Uma extensão da linguagem JavaScript",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
    {
        i: 1,
        question: "O React é __",
        answer: "Uma biblioteca JavaScript para construção de interfaces",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
    {
        i: 2,
        question: "Componentes devem iniciar com __",
        answer: "Letra maiúscula",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
    {
        i: 3,
        question: "Podemos colocar __ dentro do JSX",
        answer: "expressões",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
    {
        i: 4,
        question: "O ReactDOM nos ajuda __",
        answer: "Interagindo com a DOM para colocar componentes React na mesma",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
    {
        i: 5,
        question: "Usamos o npm para __",
        answer: "Gerenciar os pacotes necessários e suas dependências",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
    {
        i: 6,
        question: "Usamos props para __",
        answer: "Passar diferentes informações para componentes",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
    {
        i: 7,
        quesion: "Usamos estado (state) para __",
        answer: "Dizer para o React quais informações quando atualizadas devem renderizar a tela novamente",
        state: 0,
        open: false,
        turned: false,
        done: false,
    },
];
export default cards;
